=== cannam/piper/schema/extractorstaticdata.json
{
    "id": "http://vamp-plugins.org/json/schema/pluginstaticdata#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "schema for the static metadata associated with a feature extractor",
    "type": "object",
    "properties": {
	"pluginKey": {
	    "type": "string"
	},
	"basic": {
	    "$ref": "http://vamp-plugins.org/json/schema/basic#"
	},
	"maker": {
	    "type": "string"
	},
	"copyright": {
	    "type": "string"
	},
	"pluginVersion": {
	    "type": "integer"
	},
	"category": {
	    "type": "array",
	    "items": { "type": "string" }
	},
	"minChannelCount": {
	    "type": "integer"
	},
	"maxChannelCount": {
	    "type": "integer"
	},
	"parameters": {
	    "type": "array",
	    "items": { "$ref": "http://vamp-plugins.org/json/schema/parameterdescriptor#" }
	},
	"programs": {
	    "type": "array",
	    "items": { "type": "string" }
	},
	"inputDomain": {
	    "$ref": "http://vamp-plugins.org/json/schema/enums#/definitions/input_domain"
	},
	"basicOutputInfo": {
	    "type": "array",
	    "items": { "$ref": "http://vamp-plugins.org/json/schema/basic#" }
	}
    },
    "required": [ "pluginKey", "basic", "pluginVersion",
		  "minChannelCount", "maxChannelCount",
		  "inputDomain", "basicOutputInfo" ],
    "additionalProperties": false
}

=== cannam/piper/examples/pluginstaticdata.json
{"basic": {"description": "Detect percussive note onsets by identifying broadband energy rises", "identifier": "percussiononsets", "name": "Simple Percussion Onset Detector"}, "basicOutputInfo": [{"description": "Percussive note onset locations", "identifier": "onsets", "name": "Onsets"}, {"description": "Broadband energy rise detection function", "identifier": "detectionfunction", "name": "Detection Function"}], "category": ["Time", "Onsets"], "copyright": "Code copyright 2006 Queen Mary, University of London, after Dan Barry et al 2005.  Freely redistributable (BSD license)", "inputDomain": "FrequencyDomain", "pluginKey": "vamp-example-plugins:percussiononsets", "maker": "Vamp SDK Example Plugins", "maxChannelCount": 1, "minChannelCount": 1, "parameters": [{"basic": {"description": "Energy rise within a frequency bin necessary to count toward broadband total", "identifier": "threshold", "name": "Energy rise threshold"}, "defaultValue": 3, "extents": {"max": 20, "min": 0}, "unit": "dB", "valueNames": []}, {"basic": {"description": "Sensitivity of peak detector applied to broadband detection function", "identifier": "sensitivity", "name": "Sensitivity"}, "defaultValue": 40, "extents": {"max": 100, "min": 0}, "unit": "%", "valueNames": []}], "programs": [], "pluginVersion": 2}

=== cannam/piper/examples/listresponse.json
[
  {
    "basic": {
      "description": "Track the amplitude of the audio signal",
      "identifier": "amplitudefollower",
      "name": "Amplitude Follower"
    },
    "basicOutputInfo": [
      {
        "description": "The peak tracked amplitude for the current processing block",
        "identifier": "amplitude",
        "name": "Amplitude"
      }
    ],
    "category": [],
    "copyright": "Code copyright 2006 Dan Stowell; method from SuperCollider.  Freely redistributable (BSD license)",
    "inputDomain": "TimeDomain",
    "maker": "Vamp SDK Example Plugins",
    "maxChannelCount": 1,
    "minChannelCount": 1,
    "parameters": [
      {
        "basic": {
          "description": "The 60dB convergence time for an increase in amplitude",
          "identifier": "attack",
          "name": "Attack time"
        },
        "defaultValue": 0.0099999997764825821,
        "extents": {
          "max": 1,
          "min": 0
        },
        "unit": "s",
        "valueNames": []
      },
      {
        "basic": {
          "description": "The 60dB convergence time for a decrease in amplitude",
          "identifier": "release",
          "name": "Release time"
        },
        "defaultValue": 0.0099999997764825821,
        "extents": {
          "max": 1,
          "min": 0
        },
        "unit": "s",
        "valueNames": []
      }
    ],
    "pluginKey": "vamp-example-plugins:amplitudefollower",
    "pluginVersion": 1,
    "programs": []
  },
  {
    "basic": {
      "description": "Study a short section of audio and estimate its tempo, assuming the tempo is constant",
      "identifier": "fixedtempo",
      "name": "Simple Fixed Tempo Estimator"
    },
    "basicOutputInfo": [
      {
        "description": "Estimated tempo",
        "identifier": "tempo",
        "name": "Tempo"
      },
      {
        "description": "Possible tempo estimates, one per bin with the most likely in the first bin",
        "identifier": "candidates",
        "name": "Tempo candidates"
      },
      {
        "description": "Onset detection function",
        "identifier": "detectionfunction",
        "name": "Detection Function"
      },
      {
        "description": "Autocorrelation of onset detection function",
        "identifier": "acf",
        "name": "Autocorrelation Function"
      },
      {
        "description": "Filtered autocorrelation of onset detection function",
        "identifier": "filtered_acf",
        "name": "Filtered Autocorrelation"
      }
    ],
    "category": [],
    "copyright": "Code copyright 2008 Queen Mary, University of London.  Freely redistributable (BSD license)",
    "inputDomain": "FrequencyDomain",
    "maker": "Vamp SDK Example Plugins",
    "maxChannelCount": 1,
    "minChannelCount": 1,
    "parameters": [
      {
        "basic": {
          "description": "Minimum beat-per-minute value which the tempo estimator is able to return",
          "identifier": "minbpm",
          "name": "Minimum estimated tempo"
        },
        "defaultValue": 50,
        "extents": {
          "max": 360,
          "min": 10
        },
        "unit": "bpm",
        "valueNames": []
      },
      {
        "basic": {
          "description": "Maximum beat-per-minute value which the tempo estimator is able to return",
          "identifier": "maxbpm",
          "name": "Maximum estimated tempo"
        },
        "defaultValue": 190,
        "extents": {
          "max": 360,
          "min": 10
        },
        "unit": "bpm",
        "valueNames": []
      },
      {
        "basic": {
          "description": "Length of audio input, in seconds, which should be taken into account when estimating tempo.  There is no need to supply the plugin with any further input once this time has elapsed since the start of the audio.  The tempo estimator may use only the first part of this, up to eight times the slowest beat duration: increasing this value further than that is unlikely to improve results.",
          "identifier": "maxdflen",
          "name": "Input duration to study"
        },
        "defaultValue": 10,
        "extents": {
          "max": 40,
          "min": 2
        },
        "unit": "s",
        "valueNames": []
      }
    ],
    "pluginKey": "vamp-example-plugins:fixedtempo",
    "pluginVersion": 1,
    "programs": []
  },
  {
    "basic": {
      "description": "Detect percussive note onsets by identifying broadband energy rises",
      "identifier": "percussiononsets",
      "name": "Simple Percussion Onset Detector"
    },
    "basicOutputInfo": [
      {
        "description": "Percussive note onset locations",
        "identifier": "onsets",
        "name": "Onsets"
      },
      {
        "description": "Broadband energy rise detection function",
        "identifier": "detectionfunction",
        "name": "Detection Function"
      }
    ],
    "category": [],
    "copyright": "Code copyright 2006 Queen Mary, University of London, after Dan Barry et al 2005.  Freely redistributable (BSD license)",
    "inputDomain": "FrequencyDomain",
    "maker": "Vamp SDK Example Plugins",
    "maxChannelCount": 1,
    "minChannelCount": 1,
    "parameters": [
      {
        "basic": {
          "description": "Energy rise within a frequency bin necessary to count toward broadband total",
          "identifier": "threshold",
          "name": "Energy rise threshold"
        },
        "defaultValue": 3,
        "extents": {
          "max": 20,
          "min": 0
        },
        "unit": "dB",
        "valueNames": []
      },
      {
        "basic": {
          "description": "Sensitivity of peak detector applied to broadband detection function",
          "identifier": "sensitivity",
          "name": "Sensitivity"
        },
        "defaultValue": 40,
        "extents": {
          "max": 100,
          "min": 0
        },
        "unit": "%",
        "valueNames": []
      }
    ],
    "pluginKey": "vamp-example-plugins:percussiononsets",
    "pluginVersion": 2,
    "programs": []
  },
  {
    "basic": {
      "description": "Return the power spectrum of a signal",
      "identifier": "powerspectrum",
      "name": "Simple Power Spectrum"
    },
    "basicOutputInfo": [
      {
        "description": "Power values of the frequency spectrum bins calculated from the input signal",
        "identifier": "powerspectrum",
        "name": "Power Spectrum"
      }
    ],
    "category": [],
    "copyright": "Freely redistributable (BSD license)",
    "inputDomain": "FrequencyDomain",
    "maker": "Vamp SDK Example Plugins",
    "maxChannelCount": 1,
    "minChannelCount": 1,
    "parameters": [],
    "pluginKey": "vamp-example-plugins:powerspectrum",
    "pluginVersion": 1,
    "programs": []
  },
  {
    "basic": {
      "description": "Calculate the centroid frequency of the spectrum of the input signal",
      "identifier": "spectralcentroid",
      "name": "Spectral Centroid"
    },
    "basicOutputInfo": [
      {
        "description": "Centroid of the log weighted frequency spectrum",
        "identifier": "logcentroid",
        "name": "Log Frequency Centroid"
      },
      {
        "description": "Centroid of the linear frequency spectrum",
        "identifier": "linearcentroid",
        "name": "Linear Frequency Centroid"
      }
    ],
    "category": [],
    "copyright": "Freely redistributable (BSD license)",
    "inputDomain": "FrequencyDomain",
    "maker": "Vamp SDK Example Plugins",
    "maxChannelCount": 1,
    "minChannelCount": 1,
    "parameters": [],
    "pluginKey": "vamp-example-plugins:spectralcentroid",
    "pluginVersion": 2,
    "programs": []
  },
  {
    "basic": {
      "description": "Detect and count zero crossing points",
      "identifier": "zerocrossing",
      "name": "Zero Crossings"
    },
    "basicOutputInfo": [
      {
        "description": "The number of zero crossing points per processing block",
        "identifier": "counts",
        "name": "Zero Crossing Counts"
      },
      {
        "description": "The locations of zero crossing points",
        "identifier": "zerocrossings",
        "name": "Zero Crossings"
      }
    ],
    "category": [],
    "copyright": "Freely redistributable (BSD license)",
    "inputDomain": "TimeDomain",
    "maker": "Vamp SDK Example Plugins",
    "maxChannelCount": 1,
    "minChannelCount": 1,
    "parameters": [],
    "pluginKey": "vamp-example-plugins:zerocrossing",
    "pluginVersion": 2,
    "programs": []
  }
]
